# Cross-compile for Windows x86_64 with mingw-w64 (posix threads), e.g. the toolchain unpacked by
# scripts/fetch-mingw.sh:  cmake -B build-win -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-w64-x86_64.cmake
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(MINGW_ROOT "${CMAKE_CURRENT_LIST_DIR}/../third_party/mingw/usr" CACHE PATH "mingw-w64 install prefix")
if(EXISTS "${MINGW_ROOT}/bin/x86_64-w64-mingw32-g++-posix")
  set(CMAKE_C_COMPILER "${MINGW_ROOT}/bin/x86_64-w64-mingw32-gcc-posix")
  set(CMAKE_CXX_COMPILER "${MINGW_ROOT}/bin/x86_64-w64-mingw32-g++-posix")
  set(CMAKE_RC_COMPILER "${MINGW_ROOT}/bin/x86_64-w64-mingw32-windres")
  set(CMAKE_FIND_ROOT_PATH "${MINGW_ROOT}/x86_64-w64-mingw32")
else()
  set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc-posix)
  set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++-posix)
  set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
